---
language: go
sudo: false
notifications:
  email: joaosoft@gmail.com
jobs:
  include:
    - stage: test
      install:
        - go mod tyde
      os: linux
      go: master
      script:
        - go mod tidy
        - go mod vendor
        - go test -coverprofile=coverage.txt -covermode=atomic .
        - go test . -bench=. -cpu=1,2,4,8

      after_success:
        - bash <(curl -s https://codecov.io/bash)